version: '3.8'

services:
  orar-app:
    build: .
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - bubunet
networks:
  bubunet:
    external: true
